#+TITLE: Personal Mission Statement

#+begin_quote
People can't live with change if there's not a changeless core inside them.
#+end_quote

#+begin_quote
Whatever is at the center of our life will be the source of our security, guidance, wisdom and power.
#+end_quote

#+begin_quote
Wisdom is your perspective on life. Your sense of balance. Your understanding of how the various parts and principles apply and relate to each other. It embraces judgement, discernment and comprehension. It is a gestalt or oneness, an integrated wholeness.
#+end_quote

#+begin_quote
Remember that your paradigm is the source from which your attitudes and behaviours flow. A paradigm is like a pair of glasses. It affects the way you see everything in your life. If you look at things through the paradigm of correct principles, what you see in life is dramatically different from what you see through any other centered paradigm.
#+end_quote

#+begin_quote
Ultimately, man should not ask what the meaning of life is, but rather must recognize that it is he who is asked.
#+end_quote

#+begin_quote
#+end_quote

* strive for freedom.
* strive for truth.
* strive for foresight.
* there's no right answer.
* most everything is relative.
* question everything. get curious. get general.
* be an observer. get wise.
* be a hacker. design.
* be a writer. figure it out.
* don't be a slave to pleasure.
* be a stoic.
* good friends are priceless.
* everybody is human. no one's invincible. there's always a way around.
* technology makes you powerful. get powerful.
