#+TITLE: Nov4

* Pleasure
the stoics are right.
pleasure destroys your life.
it is the most cunning, ruthless destroyer of lives.
the notorious *pain* though, turns out to be a friend.
seek pain.
the kind that hurts when you grow, not the /toe-under-shoe/ pain.
pain is the one constant.
it is the one thing you can depend on.
pain won't disappoint you.
you can get it whenever you want.
it will always be with you.

don't deny pleasure though.
that would be a mistake.
you have to keep your enemies close.
don't let it hold power over you.
you should have a quota for pleasure.
for eg, i am addicted to TV shows.
so instead of secretly binging them all week, i only watch a couple of episodes a day.
if i catch myself wanting more, i know i should expect trouble.
i know that the old me is trying to make a comeback and i should be extra alert.
that's how i keep the /beast/ at bay.
* Present
the older i get, the more i believe the phrase *you live now*.
this phrase reveals one of the many shortcomings of human mind.
+we+ I tend to +think+ fantasize that once I achieved my goals, all will be well.
I will be the master of the universe.
there are no more problems. happy forever.

but that is so untrue.
problems and pain are the constants of life.
you can't esacape them.
so you better learn to live with them.

i think the reality lies somewhere between the extremes. heaven and hell.
sometimes crosssing over into their boundaries.
sometimes into heaven. sometimes into hell.
the reality is such that, staying in either extremes longer than you're supposed to, you pay a price.
sometimes with your life.
sometimes worse.

as a human, if you do nothing, you will die.
the default result is death.
that's why it takes effort to *survive*.
likewise, in life, if you do nothing you suffer.
the ideal is to stay somewhere in the middle.
you have to find something to do that keeps misery away from you.
you have to hold on to something. you need focus.

one way to do that is to focus on growth.
* Future
i don't know what i'm supposed to do in the future.
what i'm supposed to plan for.
i guess i have to figure that out myself.
piece by piece.
here's a small piece: learning.
be a learning machine.
see something fascinating?
dive into the code.
